### ISSUE TITLE
Proposal: New DSL

### ISSUE THREAD

**Issue by mvalipour** [deliveroo/materialist#18]
### Why

It's wrong/confusing to call each field `materialize` because "materialize" is a verb that is used for the whole action:

> We "materialize" the resource

Therefore, each field should be something like `include`

```ruby
class FoobarMaterializer
  include Materialist::Materializer

  materialize_to :foobar
  includes :name
  includes :age, as: :how_old

  materialize_link :city

  from_link :city do
    includes :timezone

    from_link :country do
      includes :tld, as: :country_tld
    end
  end
end

```

**Comment by robladbrook** [comment]
You could take a more "database" style naming approach:

```ruby
class FoobarMaterializer
  include Materialist::Materializer

  persist_to :foobar
  capture :name
  capture :age, as: :how_old

  capture_relation :city

  relation :city do
    capture :timezone

    relation :country do
      capture :tld, as: :country_tld
    end
  end
end

```

**Comment by knaveofdiamonds** [comment]
Think `includes` is potentially confusing because it is so close to ruby's `include`. Maybe something as simple as `attribute`, `field` or `property`? i.e. noun rather than verb.

**Comment by mvalipour** [comment]
@knaveofdiamonds it needs to be something that would read nicely and clearly when saying `include :id, as: :source_id`

To not being confusing which one is key on resource and which one is column name is quite important.

**Comment by mvalipour** [comment]
@robladbrook `materialize_relation` kinda need to say `materialize` because it means we are actually calling into the materializer of the relation url.

**Comment by novotnyjakub** [comment]
I like @robladbrook approach and I like the fact that the dsl is consistently using verbs in the same form "do this, do that".

`capture`, `use` look good to me
